# format = '$all$directory$character'
add_newline = false

# A minimal left prompt
format = """$directory$character"""
#palette = "rosepine"

# move the rest of the prompt to the right
#right_format = """$all"""
right_format = """
$username\
$hostname\
$kubernetes\
$fossil_branch\
$git_branch\
$git_commit\
$git_state\
$git_metrics\
$git_status\
$docker_context\
$package\
$cmake\
$deno\
$golang\
$guix_shell\
$java\
$kotlin\
$nim\
$nodejs\
$ocaml\
$opa\
$php\
$python\
$rust\
$swift\
$terraform\
$zig\
$buf\
$nix_shell\
$aws\
$gcloud\
$azure\
$env_var\
$sudo\
$cmd_duration\
$status\
$os\
$container\
$shell\
"""

[directory]
#truncation_length = 2
#truncation_symbol = '…/'
# disabled = true

# Replace the '❯' symbol in the prompt with '➜'
#[character] # The name of the module we are configuring is 'character'
#success_symbol = '[➜](bold green)' # The 'success_symbol' segment is being set to '➜' with the color 'bold green'

[azure]
disabled = false
format = 'on [$symbol($subscription)]($style) '
symbol = '󰠅 '
style = 'blue bold'

[aws]
format = 'on [$symbol($profile )(\($region\) )]($style)'
style = 'bold blue'
symbol = "  "

[golang]
format = '[ $version](bold cyan) '

[kubernetes]
symbol = '☸'
disabled = false
detect_files = ['k8s', 'Dockerfile']
detect_extensions = ['yaml']
format = '[$symbol$context( \($namespace\))]($style) '

[palettes.rosepine]
black = "#26233a"
red = "#eb6f92"
green = "#31748f"
yellow = "#f6c177"
blue = "#9ccfd8"
magenta = "#c4a7e7"
cyan = "#ebbcba"
white = "#e0def4"
