# format = '$all$directory$character'
add_newline = false

# A minimal left prompt
format = """$directory$character"""
palette = "melange"

# move the rest of the prompt to the right
#right_format = """$all"""

right_format = """
$username\
$hostname\
$package\
$git_branch\
$git_commit\
$git_state\
$git_metrics\
$git_status\
$nix_shell\
$kubernetes\
$nodejs\
$php\
$ocaml\
$zig\
$azure\
$aws\
"""

[directory]
#truncation_length = 2
#truncation_symbol = '…/'
# disabled = true
# style = "bold fg:#E49B5D"
style = ''
# style = '#A98A78'

# Replace the '❯' symbol in the prompt with '➜'
[character] # The name of the module we are configuring is 'character'
# success_symbol = '[➜](#C1A78E)' # The 'success_symbol' segment is being set to '➜' with the color 'bold green'
# error_symbol = '[➜](#C1A78E)' # The 'success_symbol' segment is being set to '➜' with the color 'bold green'
disabled = true

[azure]
disabled = false
format = '[$symbol($subscription)]($style) '
symbol = '󰠅 '
style = ''

[aws]
style = ''
format = '[$symbol($profile )(\($region\) )]($style)'
symbol = "  "

[git_branch]
disabled = false
style = ''
format = '[$symbol($branch)]($style) '

[git_commit]
disabled = true
style = ''

[git_state]
disabled = true
style = ''

[git_metrics]
disabled = true
style = ''

[git_status]
disabled = true
style = ''

[package]
disabled = false
format = '[󰏗 $version]($style) '
style = ''
display_private=true

[php]
format = '[ ($version)]($style)'
style = ''

[ocaml]
format = '[ ($version )(\($switch_indicator$switch_name\) )]($style)'
style = ''

[zig]
format = '[ ($version )]($style)'
style = ''

[nodejs]
format = '[$symbol($version)]($style)'
style = ''

[lua]
symbol = '[ $version](#C1A78E)'

[golang]
format = '[ $version](#C1A78E) '

[nix_shell]
disabled = true
impure_msg = '[impure shell](bold red)'
pure_msg = '[pure shell](bold green)'
unknown_msg = '[unknown shell](bold yellow)'
format = '[ $state( \($name\))](bold blue) '

[kubernetes]
symbol = '☸ '
disabled = false
detect_extensions = ['yaml']
style = ''
format = '[$symbol$context( \($namespace\))]($style) '
# detect_files = [
#     "*values.yaml",     # Matches any file that ends with -values.yaml
#     "*deployment.yaml",  # Matches any file that includes deployment.yaml
#     "*service.yaml",     # Matches any file that includes service.yaml
#     "*ingress.yaml",     # Matches any file that includes ingress.yaml
#     "*Chart.yaml",       # Matches any file that includes Chart.yaml
#     "*configmap.yaml",   # Matches any file that includes configmap.yaml
#     "*secrets.yaml",     # Matches any file that includes secrets.yaml
#     "*persistentvolume.yaml",  # Matches any file that includes persistentvolume.yaml
#     "*persistentvolumeclaim.yaml",  # Matches any file that includes persistentvolumeclaim.yaml
#     "*namespace.yaml",   # Matches any file that includes namespace.yaml
#     "*pvc.yaml"          # Matches any file that includes pvc.yaml
# ]
detect_folders = [
    "k8s", "helm-charts"
]

[palettes.rosepine]
black = "#26233a"
red = "#eb6f92"
green = "#31748f"
yellow = "#f6c177"
blue = "#9ccfd8"
magenta = "#c4a7e7"
cyan = "#ebbcba"
white = "#e0def4"

[palettes.melange]
bright_black="#867462"
bright_blue="#A3A9CE"
right_cyan="#89B3B6"
bright_green="#85B695"
bright_magenta="#CF9BC2"
bright_red="#D47766"
bright_white="#ECE1D7"
bright_yellow="#EBC06D"
dark_black="#292522"
dark_blue="#273142"
dark_cyan="#253333"
dark_green="#233524"
dark_magenta="#422741"
dark_red="#7D2A2F"
dark_white="#403A36"
dark_yellow="#8B7449"
black="#34302C"
blue="#7F91B2"
cyan="#7B9695"
green="#78997A"
magenta="#B380B0"
red="#BD8183"
white="#C1A78E"
yellow="#E49B5D"
