# Change the default Omarchy look'n'feel

# https://wiki.hyprland.org/Configuring/Variables/#general
general {
    # No gaps between windows or borders
    gaps_in = 4
    gaps_out = 8
    # border_size = 0

    # Use master layout instead of dwindle
    # layout = master
}


decoration {
    # Use round window corners
    rounding = 8
}

# Force software cursors to fix black box on rotated AMD monitor (Hyprland 0.54 bug)
# Can be removed once fixed in a later Hyprland version (check with: hyprctl version)
cursor {
    no_hardware_cursors = true
}

# https://wiki.hypr.land/Configuring/Variables/#layout
layout {
    # Avoid overly wide single-window layouts on wide screens
    # single_window_aspect_ratio = 1 1
}
