import = ["~/.config/alacritty/catppuccin-mocha.toml"]

[env]
TERM = "xterm-256color"

[window]
decorations = "None"
padding = { x = 1, y = 1 }
opacity = 0.95
dynamic_padding = true

[mouse]
hide_when_typing = true

[cursor.style]
shape = "Block"
blinking = "On"

[selection]
save_to_clipboard = true

[scrolling]
history = 100000
multiplier = 3

[font]
size = 14.0

[font.normal]
family = "BerkeleyMono Nerd Font Mono"
style = "Regular"

[font.bold]
family = "BerkeleyMono Nerd Font Mono"
style = "Bold"

[font.italic]
family = "BerkeleyMono Nerd Font Mono"
style = "Italic"

[font.bold_italic]
family = "BerkeleyMono Nerd Font Mono"
style = "Bold Italic"

[colors.normal]
black = "0x1D202F"
red = "0xf7768e"
green = "0x9ece6a"
yellow = "0xe0af68"
blue = "0x7aa2f7"
magenta = "0xbb9af7"
cyan = "0x7dcfff"
white = "0xa9b1d6"

[colors.bright]
black = "0x414868"
red = "0xf7768e"
green = "0x9ece6a"
yellow = "0xe0af68"
blue = "0x7aa2f7"
magenta = "0xbb9af7"
cyan = "0x7dcfff"
white = "0xc0caf5"

[shell]
program = "/bin/zsh"
args = ["-c", "zsh ~/personal/.dotfiles/.local/bin/tmux-launcher; zsh"]

